name: Translate Chinese Issues

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'The issue number to translate'
        required: true
        type: string
  issues:
    types: [opened]

permissions:
  issues: write # Grant permission to edit issues

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - uses: emqx/translate-issue-action@ad0fb7225a7da9972c18c628136bbf724dae9622 # v1.0.2
      with:
        issue_number: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.issue_number || github.event.issue.number }}
        gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
