name: Run Boot tests

concurrency:
  group: boot-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      builder:
        required: true
        type: string

permissions:
  contents: read

jobs:
  boot:
    runs-on: ubuntu-22.04
    container: ${{ inputs.builder }}
    env:
      PROFILE: ${{ matrix.profile }}
    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx-enterprise
    steps:
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: ${{ matrix.profile }}
      - name: extract artifact
        run: |
          unzip -o -q ${{ matrix.profile }}.zip
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: make ${{ matrix.profile }}
      - name: install bats
        run: |
          apt-get update
          apt-get install -y bats
      - run: bats ./scripts/test/emqx-boot.bats
